DROP TABLE IF EXISTS mpa_ratings CASCADE;
DROP TABLE IF EXISTS genres CASCADE;
DROP TABLE IF EXISTS films CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS film_genres CASCADE;
DROP TABLE IF EXISTS likes CASCADE;
DROP TABLE IF EXISTS friendships CASCADE;

CREATE TABLE IF NOT EXISTS mpa_ratings (
mpa_id INTEGER PRIMARY KEY,
code VARCHAR(5) NOT NULL,
description VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS genres (
genre_id INTEGER PRIMARY KEY,
name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
film_id BIGINT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
description VARCHAR(200),
release_date DATE NOT NULL,
duration INTEGER NOT NULL,
mpa_id INTEGER REFERENCES mpa_ratings(mpa_id)
);

CREATE TABLE IF NOT EXISTS users (
user_id BIGINT AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(255) NOT NULL UNIQUE,
login VARCHAR(50) NOT NULL UNIQUE,
name VARCHAR(255),
birthday DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS film_genres (
film_id BIGINT REFERENCES films(film_id) ON DELETE CASCADE,
genre_id INTEGER REFERENCES genres(genre_id),
PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS likes (
film_id BIGINT REFERENCES films(film_id) ON DELETE CASCADE,
user_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS friendships (
user_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
friend_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
PRIMARY KEY (user_id, friend_id)
);
